In [1]:
scores = [78, 69, 65]
new_scores = []

for score in scores:
    new_scores.append(score + 3)

new_scores

[81, 72, 68]

In [3]:
scores = [78, 69, 65]
new_scores = [score + 3 for score in scores]    # List comprehension
new_scores

[81, 72, 68]

In [7]:
scores = [78, 69, 65]

scores

[78, 69, 65]

In [12]:
import numpy as np
np_scores = np.array(scores)
np_scores.sum()
np_scores.mean()
np_scores.std()
np_scores.var()
np_scores.min()
np_scores.max()
np_scores.argmax()
np_scores.argmin()
np_scores.cumsum()
np_scores.cumprod()
np_scores.sort()
np.median(np_scores)

np.float64(69.0)

In [17]:
students = np.array([[67,94,65], [88,82,78], [75,90,85]])
students.ndim,  students.size, students.shape, students.dtype

(2, 9, (3, 3), dtype('int64'))

In [19]:
students[0,0]


np.int64(67)

In [20]:
students[0:2,:]

array([[67, 94, 65],
       [88, 82, 78]])

In [21]:
students[-1,:]

array([75, 90, 85])

In [22]:
students[:,0]

array([67, 88, 75])

In [23]:
students[:,:2]

array([[67, 94],
       [88, 82],
       [75, 90]])

In [25]:
students[0,0]=100
students

array([[100,  94,  65],
       [ 88,  82,  78],
       [ 75,  90,  85]])